[options]
addons_path = /mnt/extra-addons,/usr/lib/python3/dist-packages/odoo/addons
data_dir = /var/lib/odoo
admin_passwd = admin
db_host = odoo-db
db_port = 5432
db_user = odoo
db_password = odoo
db_maxconn = 64
without_demo = False
list_db = True
log_level = info
workers = 0
max_cron_threads = 1
proxy_mode = False

; Dev only. Prod'da list_db=False, admin_passwd değişir, proxy_mode=True.
